Improvement1
peninah98/code-quality pull request #5
Opened 2023-10-17 09:11 UTC by peninah98

2023-10-17 11:09 UTC, ishimwe07 requested changes
The codes looks good but I left you some comments that I think can be used or considered and make the codes way better.

2023-10-17 11:09 UTC, ishimwe07 commented on src/improvement-1.js
>  export default function cntRbt(ls) {
- Can you try to name the function more descriptive name, because It's very hard to understand what cntRbt mean in order to know what function is performing.
- The same goes even on parameters naming (I think that ls is not really descriptive).  Probably you can consider making it way better.

2023-10-17 11:09 UTC, ishimwe07 commented on src/improvement-2.js
>    return items.filter((item)=> item.type === 'Food')
Since this is one line function can't you consider using implicit return and remove some unnecessary codes like curry brackets or return keyword.

2023-10-17 11:09 UTC, ishimwe07 commented on src/improvement-3.js
> +}
Since this is one line function can't you consider using implicit return and remove some unnecessary codes like curry brackets or return keyword.

2023-10-17 11:09 UTC, ishimwe07 commented on src/passwordValidation.js
>    }
Probably you can consider putting the return in front of if condition and remove the curry brackets since it's one line.

2023-10-17 11:09 UTC, ishimwe07 commented on src/passwordValidation.js
> +  const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z0-9]{10}$/
Can you consider adding more description on this regex, so that anyone who can read you codes can understand what it is about.

2023-10-17 11:09 UTC, ishimwe07 commented on src/passwordValidation.js
> +  if (password < 4) return false
On the upper part of your codes, password was a string and here I don't know how the comparison of a string and a number is serving any purpose. If there isn't It can be removed but if there is you can consider comparing values of same types to have a better results.

2023-10-20 09:59 UTC, devfabien approved these changes
This file LGTM

2023-11-19 10:55 UTC, merged